config/routes.rb
Appstore::Engine.routes.draw do
  
  namespace :admin do
    resources :users
    resources :mobile_apps
  end

  mount Alohomora::Engine, at: "/", as: "alohomora"
  resources :welcome, only: [:index]
  root :to => 'welcome#index'
end

app/models/appstore/mobile_app.rb
module Appstore
  class MobileApp < ActiveRecord::Base
    has_attached_file :plist, 
                      :url => "/assets/appstore/mobile_app/plists/:id/:basename.:extension",
                      :path => ":rails_root/public/assets/appstore/mobile_app/plists/:id/:basename.:extension"
    has_attached_file :ipa, 
                      :url => "/assets/appstore/mobile_app/ipas/:id/:basename.:extension",
                      :path => ":rails_root/public/assets/appstore/mobile_app/ipas/:id/:basename.:extension"
    has_attached_file :icon, 
                      :url => "/assets/appstore/mobile_app/icons/:id/:style/:basename.:extension",
                      :path => ":rails_root/public/assets/appstore/mobile_app/icons/:id/:style/:basename.:extension",
                      :styles => { :thumb => "72x72>" }
    attr_accessible :name, :organization_id, :plist, :ipa, :icon, :organization
    belongs_to :organization
  end
end

app/models/user_decorator.rb
User.class_eval do
  attr_accessible :first_name, :last_name
  
  def belongs_to_org?(organization)
    org_ids = self.organizations.map { |org| org.id }
    return org_ids.include?(organization.id)
  end
end

app/controllers/appstore/admin/application_controller.rb
module Appstore
  class Admin::ApplicationController < ApplicationController
    def admin?
      puts "****************************" + current_user.last_name.to_s + ", " + current_user.admin?.to_s
      throw(:warden) if !current_user.admin?
    end
  end
end

app/controllers/appstore/admin/mobile_apps_controller.rb
module Appstore
  class Admin::MobileAppsController < Admin::ApplicationController
    before_filter :authenticate!, :admin?
    
    def index
      @mobile_apps = MobileApp.all
    end

    def show
      @mobile_app = MobileApp.find(params[:id])
    end

    def new
      @mobile_app = MobileApp.new
    end

    def create
      @mobile_app = MobileApp.new(params[:mobile_app])
      if @mobile_app.save
        redirect_to admin_mobile_app_path(@mobile_app), :notice => "Successfully created mobile app."
      else
        render :new
      end
    end

    def edit
      @mobile_app = MobileApp.find(params[:id])
    end

    def update
      @mobile_app = MobileApp.find(params[:id])
      if @mobile_app.update_attributes(params[:mobile_app])
        redirect_to admin_mobile_app_path(@mobile_app), :notice  => "Successfully updated mobile app."
      else
        render :edit
      end
    end

    def destroy
      @mobile_app = MobileApp.find(params[:id])
      @mobile_app.destroy
      redirect_to admin_mobile_apps_path, :notice => "Successfully destroyed mobile app."
    end
  end
end

app/controllers/appstore/admin/users_controller.rb
module Appstore
  class Admin::UsersController < Admin::ApplicationController
    before_filter :authenticate!, :admin?
    
    def index
      @users = User.all
    end
    
    def show
      @user = User.find(params[:id])
    end
    
    def edit
      @user = User.find(params[:id])
    end
    
    def update
      @user = User.find(params[:id])
      
      # Remove existing organization relationships
      @user.organizations = []
      
      # Assign organizations relationships
      org_ids = params[:organization_id]
      if org_ids
        if (org_ids.class != Array)
          org_ids = [org_ids]
        end
      
        org_ids.each do |org_id|
          @user.organizations.push(Alohomora::Organization.find(org_id))
        end
      end
      
      if @user.update_attributes(params[:user])
        redirect_to admin_user_path(@user), :notice  => "Successfully updated user."
      else
        render :edit
      end
    end
    
    def destroy
      @user = User.find(params[:id])
      @user.destroy
      redirect_to admin_users_path, :notice => "Successfully destroyed mobile app."
    end
  end
end

app/controllers/appstore/alohomora/sessions_controller_decorator.rb
Alohomora::SessionsController.class_eval do
  def create
    warden.authenticate!
    redirect_to appstore.welcome_index_path, notice: "Signed in successfully."
  end

  def destroy
    env['warden'].logout
    redirect_to alohomora.signin_path, notice: "Signed out successfully."
  end

end

app/controllers/appstore/application_controller.rb
module Appstore
  class ApplicationController < ActionController::Base
  end
end

app/controllers/appstore/welcome_controller.rb
require_dependency "appstore/application_controller"

module Appstore
  class WelcomeController < ApplicationController
    before_filter :authenticate!
    
    def index
      # Only show apps that belong to the user's organizations
      org_ids = current_user.organizations.map { |org| org.id }
      @mobile_apps = MobileApp.where(:organization_id => org_ids)
    end
    
  end
end

app/helpers/appstore/application_helper.rb
module Appstore
  module ApplicationHelper
  end
end

app/helpers/appstore/mobile_apps_helper.rb
module Appstore
  module MobileAppsHelper
  end
end

app/helpers/appstore/welcome_helper.rb
module Appstore
  module WelcomeHelper
  end
end

app/helpers/error_messages_helper.rb
module ErrorMessagesHelper
  # Render error messages for the given objects. The :message and :header_message options are allowed.
  def error_messages_for(*objects)
    options = objects.extract_options!
    options[:header_message] ||= I18n.t(:"activerecord.errors.header", :default => "Invalid Fields")
    options[:message] ||= I18n.t(:"activerecord.errors.message", :default => "Correct the following errors and try again.")
    messages = objects.compact.map { |o| o.errors.full_messages }.flatten
    unless messages.empty?
        # forced as error but may not abstractly always be the case
      content_tag(:div, :class => "alert-message block-message error") do
        list_items = messages.map { |msg| content_tag(:li, msg.html_safe) }
        content_tag(:h2, options[:header_message].html_safe) + content_tag(:p, options[:message].html_safe) + content_tag(:ul, list_items.join.html_safe)
      end
    end
  end
  
  def display_flash_message
  	partials = String.new
	  flash.each do |key, value|  
      css_class = key.to_s.eql?('notice') ? 'success' : 'error'
      partials << render( :partial => 'share/flash', :locals => { :css => css_class, :message => value }) 
    end
	  partials.html_safe
  end

  module FormBuilderAdditions
    def error_messages(options = {})
      @template.error_messages_for(@object, options)
    end
  end
end

ActionView::Helpers::FormBuilder.send(:include, ErrorMessagesHelper::FormBuilderAdditions)

app/helpers/layout_helper.rb
# These helper methods can be called in your template to set variables to be used in the layout
# This module should be included in all views globally,
# to do so you may need to add this line to your ApplicationController
#   helper :layout
module LayoutHelper
  def title(page_title, show_title = true)
    content_for(:title) { h(page_title.to_s) }
    @show_title = show_title
  end

  def show_title
    @show_title
  end

  def stylesheet(*args)
    content_for(:head) { stylesheet_link_tag(*args) }
  end

  def javascript(*args)
    content_for(:head) { javascript_include_tag(*args) }
  end
  
  def app_name
    Rails.application.class.to_s.split("::").first
  end
end

app/views/appstore/admin/mobile_apps/_form.html.erb
<%= form_for @mobile_app, { :html => { :id => 'mobile-app-form', :class => 'form-horizontal', :multipart => true }, :url => (@mobile_app.id ? admin_mobile_app_path(@mobile_app) : admin_mobile_apps_path) } do |f| %>
  <fieldset>
    <legend><%= form_action_title %> Mobile App</legend>
    <div class="control-group">
      <%= f.label :name, :class => 'control-label' %>
      <div class="controls">
        <%= f.text_field :name, :class => 'text_field' %>
      </div>
    </div>
    <div class="control-group">
      <%= f.label :plist, :class => 'control-label' %>
      <div class="controls">
        <% if !(@mobile_app.plist_file_name == nil) %>
          <span><%= @mobile_app.plist_file_name %></span>
        <% end %>
        <%= f.file_field :plist %>
      </div>
    </div>
    <div class="control-group">
      <%= f.label :ipa, :class => 'control-label' %>
      <div class="controls">
        <% if !(@mobile_app.ipa_file_name == nil) %>
          <span><%= @mobile_app.ipa_file_name %>
            (<%= @mobile_app.ipa.url %>)</span>
        <% end %>
        <%= f.file_field :ipa %>
      </div>
    </div>
    <div class="control-group">
      <%= f.label :icon, :class => 'control-label' %>
      <div class="controls">
        <% if !(@mobile_app.icon_file_name == nil) %>
          <span><%= image_tag @mobile_app.icon.url(:thumb) %></span>
          <span><%= @mobile_app.icon_file_name %> (<%= @mobile_app.icon.url(:thumb) %>)</span><br>
        <% end %>
        <%= f.file_field :icon %>
      </div>
    </div>
    <div class="control-group">
      <%= f.label :organization, :class => 'control-label' %>
      <div class="controls">
        <%= collection_select(:mobile_app, :organization_id, Alohomora::Organization.all, :id, :name, :prompt => true) %>
      </div>
    </div>
    <div class="form-actions">
      <%= f.submit nil, :class => 'btn btn-primary' %>
      <%= link_to 'Cancel', admin_mobile_apps_path, :class => 'btn' %>
    </div>
  </fieldset>
<% end %>

app/views/appstore/admin/mobile_apps/edit.html.erb
<%= render :partial => 'form', :locals => { :form_action_title => 'Edit' } %>

app/views/appstore/admin/mobile_apps/index.html.erb
<% #title "Mobile Apps" %>

<div class="well">
	<table class="table table-striped">
	  <thead>
  	  <tr>
  	    <th>Name</th>
        <th></th>
        <th></th>
        <th></th>
  	  </tr>
  	</thead>
  	<tbody>
  	  <% @mobile_apps.each do |mobile_app| %>
  	    <tr>
  	      <td><%= mobile_app.name %></td>
  	      <td><%= link_to "Show", admin_mobile_app_path(mobile_app), :class => 'btn btn-mini btn-primary' %></td>
  	      <td><%= link_to "Edit", edit_admin_mobile_app_path(mobile_app), :class => 'btn btn-mini' %></td>
  	      <td><%= link_to "Destroy", admin_mobile_app_path(mobile_app), :confirm => 'Are you sure?', :method => :delete, :class => 'btn btn-mini btn-danger' %></td>
  	    </tr>
  	  <% end %>
  	</tbody>
	</table>
</div>
<p><%= link_to "New Mobile App", new_admin_mobile_app_path, :class => 'btn primary' %></p>

app/views/appstore/admin/mobile_apps/new.html.erb
<%= render :partial => 'form', :locals => { :form_action_title => 'New' } %>

app/views/appstore/admin/mobile_apps/show.html.erb
<% #title "Mobile App Details" %>

<div class="well">
  <p>
    <strong>Name:</strong>
	  <%= @mobile_app.name %>
  </p>
  <p>
    <strong>Icon:</strong>
	  <% if !(@mobile_app.icon_file_name == nil) %>
	    <%= image_tag @mobile_app.icon.url(:thumb) %>
	  <% else %>
	    None
	  <% end %>
  </p>
  <p>
    <strong>plist:</strong>
    <% if !(@mobile_app.plist_file_name == nil) %>
	    <%= link_to "View", @mobile_app.plist.url %>
	  <% else %>
	    None
    <% end %>
  </p>
  <p>
    <strong>ipa:</strong>
    <% if !(@mobile_app.ipa_file_name == nil) %>
	    <%= link_to "Download", @mobile_app.ipa.url %>
	  <% else %>
	    None
    <% end %>
  </p>
  <p>
    <strong>Organization:</strong>
    <% org_id = @mobile_app.organization_id %>
    <% if org_id %>
	    <%= Alohomora::Organization.find(org_id).name %>
	  <% else %>
	    None
    <% end %>
  </p>
  </div>
<p>
  <%= link_to "Edit", edit_admin_mobile_app_path(@mobile_app), :class => 'btn' %> |
  <%= link_to "Destroy", admin_mobile_app_path(@mobile_app), :confirm => 'Are you sure?', :method => :delete, :class => 'btn' %> |
  <%= link_to "View All", admin_mobile_apps_path, :class => 'btn btn-danger' %>
</p>

app/views/appstore/admin/users/_form.html.erb
<%= form_for @user, {:html => { :id => 'user-form', :class => 'form-horizontal' }, :url => admin_user_path(@user) } do |f| %>
  <fieldset>
    <legend><%= form_action_title %> User</legend>
    <div class="control-group">
      <%= f.label :first_name, :class => 'control-label' %>
      <div class="controls">
        <%= f.text_field :first_name, :class => 'text_field' %>
      </div>
    </div>
    <div class="control-group">
      <%= f.label :last_name, :class => 'control-label' %>
      <div class="controls">
        <%= f.text_field :last_name, :class => 'text_field' %>
      </div>
    </div>
    <div class="control-group">
      <%= f.label :email, :class => 'control-label' %>
      <div class="controls">
        <%= f.text_field :email, :class => 'text_field' %>
      </div>
    </div>
    <div class="control-group">
      <%= f.label :is_admin, :class => 'control-label' %>
      <div class="controls">
        <%= f.check_box :admin %>
      </div>
    </div>
    <h4>Organizations</h4>
    <% Alohomora::Organization.all.each do |org| %>
      <div class="control-group">
        <label class="control-label"><%= org.name %></label>
        <div class="controls">
          <input name="organization_id[]" type="checkbox" value="<%= org.id %>"
            <% if @user.belongs_to_org?(org) %>
              checked="checked"
            <% end %>
          />
        </div>
      </div>
    <% end %>
    <div class="form-actions">
      <%= f.submit nil, :class => 'btn btn-primary' %>
      <%= link_to 'Cancel', admin_users_path, :class => 'btn' %>
    </div>
  </fieldset>
<% end %>

app/views/appstore/admin/users/edit.html.erb
<%= render :partial => 'form', :locals => { :form_action_title => 'Edit' } %>

app/views/appstore/admin/users/index.html.erb
<% #title "Mobile Apps" %>

<div class="well">
	<table class="table table-striped">
	  <thead>
  	  <tr>
  	    <th>Name</th>
        <th></th>
        <th></th>
        <th></th>
  	  </tr>
  	</thead>
  	<tbody>
  	  <% @users.each do |user| %>
  	    <tr>
  	      <td><%= user.last_name + ", " + user.first_name %></td>
  	      <td><%= link_to "Show", admin_user_path(user), :class => 'btn btn-mini btn-primary' %></td>
  	      <td><%= link_to "Edit", edit_admin_user_path(user), :class => 'btn btn-mini' %></td>
  	      <td><%= link_to "Destroy", admin_user_path(user), :confirm => 'Are you sure?', :method => :delete, :class => 'btn btn-mini btn-danger' %></td>
  	    </tr>
  	  <% end %>
  	</tbody>
	</table>
</div>

app/views/appstore/admin/users/new.html.erb
<%= render :partial => 'form', :locals => { :form_action_title => 'New' } %>

app/views/appstore/admin/users/show.html.erb
<% #title "Mobile App Details" %>

<div class="well">
  <p>
    <strong>Name:</strong>
	  <%= @user.last_name + ", " + @user.first_name %>
  </p>
  <p>
    <strong>Email:</strong>
	  <%= @user.email %>
  </p>
  <p>
    <strong>Organization(s):</strong>
    <% orgs_string = "" %>
    <% @user.organizations.each do |org| %>
      <% if @user.organizations.index(org) > 0 %>
        <% orgs_string += ", " %>
      <% end %>
      <% orgs_string += org.name %>
    <% end %>
    <%= orgs_string %>
  </p>
  <p>
    <strong>Is Admin:</strong>
    <% if @user.admin? %>
      Yes
    <% else %>
      No
    <% end %>
  </p>
  </div>
<p>
  <%= link_to "Edit", edit_admin_user_path(@user), :class => 'btn' %> |
  <%= link_to "Destroy", edit_admin_user_path(@user), :confirm => 'Are you sure?', :method => :delete, :class => 'btn' %> |
  <%= link_to "View All", admin_users_path, :class => 'btn btn-danger' %>
</p>

app/views/appstore/welcome/index.html.erb
<h1>Mobile Apps <small>Available to install to your iOS device</small></h1>
<% if @mobile_apps.length > 0 %>
  <% @mobile_apps.each do |mobile_app| %>
  	<div class="mobile-apps-gallery well">
      <a href="itms-services://?action=download-manifest&url=http://<%= request.host_with_port + mobile_app.plist.url %>"><%= image_tag mobile_app.icon.url(:thumb) %></a>
      <h2><%= mobile_app.name %></h2>
      <p>Tap the app icon to install to your iOS device</p>
    </div>
  <% end %>
<% else %>
  <p>There are no mobile apps available for installation.</p>
<% end %>

app/views/layouts/appstore/application.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <title><%= content_for?(:title) ? yield(:title) : "Entropi App Store" %></title>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta name="description" content="">
    <meta name="author" content="">
    <%= csrf_meta_tags %>
    <%= yield(:head) %>

    <%= stylesheet_link_tag "appstore/application", :media => "all" %>
    
    <style type="text/css">
      body {
        padding-top: 60px;
        padding-bottom: 40px;
      }
      .sidebar-nav {
        padding: 9px 0;
      }
    </style>
    
    <!--[if lt IE 9]>
      <script src="//html5shim.googlecode.com/svn/trunk/html5.js"></script>
    <![endif]-->

    <link rel="shortcut icon" href="images/favicon.ico">
    <link rel="apple-touch-icon" href="images/apple-touch-icon.png">
    <link rel="apple-touch-icon" sizes="72x72" href="images/apple-touch-icon-72x72.png">
    <link rel="apple-touch-icon" sizes="114x114" href="images/apple-touch-icon-114x114.png">
  </head>

  <body>

    <div class="navbar navbar-fixed-top">
      <div class="navbar-inner">
          <div class="container">
          <a class="btn btn-navbar" data-toggle="collapse" data-target=".nav-collapse">
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </a>
          <a class="brand" href="#">Entropi App Store</a>
          <div class="nav-collapse">
            <ul class="nav">
              <li class="active"><a href="#">Home</a></li>
              <li><a href="#about">About</a></li>
              <li><a href="#contact">Contact</a></li>
            </ul>
            <p class="navbar-text pull-right">Logged in as <a href="#">username</a></p>
          </div><!--/.nav-collapse -->
        </div>
      </div>
    </div>
    
    <div class="container">
      <div class="row">
        <div class="span3">
          <div class="well sidebar-nav">
            <ul class="nav nav-list">
              <li class="nav-header">Sidebar</li>
              <li><a href="#">Link</a></li>
              <li><a href="#">Link</a></li>
              <li><a href="#">Link</a></li>
                          <li><a href="#">Link</a></li>
              <li><a href="#">Link</a></li>
              <li><a href="#">Link</a></li>
                          <li><a href="#">Link</a></li>
              <li><a href="#">Link</a></li>
              <li><a href="#">Link</a></li>
            
              <li class="nav-header">Sidebar</li>
              <li><a href="#">Link</a></li>
              <li><a href="#">Link</a></li>
              <li><a href="#">Link</a></li>
                          <li><a href="#">Link</a></li>
              <li><a href="#">Link</a></li>
              <li><a href="#">Link</a></li>
                          <li><a href="#">Link</a></li>
              <li><a href="#">Link</a></li>
              <li><a href="#">Link</a></li>
            
            </ul>
          </div><!--/.well -->
        </div><!--/span-->
        <div class="span9">
          <%= yield %>
        </div><!--/span-->
      </div><!--/row-->

      <hr>

      <footer>
        <p> &copy;  2012</p>
      </footer>

    </div><!--/.fluid-container-->
    
    <%= javascript_include_tag "application" %>

  </body>
</html>

app/views/share/_flash.html.erb
<div class="alert-message <%%= css %>">
 <a class="close" href="#">×</a>
 <p id="error"><%%= message %></p>
</div>